import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import Providers from "@/shared/components/providers";

const myFont = localFont({
  src: "../shared/fonts/Vazir.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${myFont.className} h-full antialiased`}>
      <body className="min-h-screen">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
