import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Providers from "@/shared/components/providers";
import { ToastContainer } from "react-toastify";

const myFont = localFont({
  src: "../shared/fonts/Vazir.woff2",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full">
      <body className={`${myFont.className} h-full antialiased`}>
        <Providers>{children}</Providers>
        <ToastContainer rtl position="bottom-center" />
      </body>
    </html>
  );
}
