import Navbar from "@/shared/components/navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8" dir="rtl">
      <Navbar />
      {children}
    </main>
  );
}
